version: '3'
services:

  load-balancer:
    build:
      context: ./load-balancer
      dockerfile: Dockerfile
    volumes:
      - ./config/eds-filesys-lb.yaml:/etc/lb.yaml:ro
#     - ./config/static-lb.yaml:/etc/lb.yaml:ro
      - ./config:/config
#   networks:
#     - envoymesh
    expose:
      - "80"
      - "8001"
    ports:
      - "8000:80"
      - "8001:8001"

  service1:
    build:
      context: ./helloworld
      dockerfile: Dockerfile
#   volumes:
#     - ./helloworld/service-envoy.yaml:/etc/service-envoy.yaml
#   networks:
#     envoymesh:
#       aliases:
#         - service1
    environment:
      - SERVICE_CLUSTER=helloworld
    expose:
      - "80"
      - "50051"
    ports:
      - 9001:50051

  service2:
    build:
      context: ./helloworld
      dockerfile: Dockerfile
#   volumes:
#     - ./helloworld/service-envoy.yaml:/etc/service-envoy.yaml
#   networks:
#     envoymesh:
#       aliases:
#         - service1
    environment:
      - SERVICE_CLUSTER=helloworld
    expose:
      - "80"
      - "50051"
    ports:
      - 9002:50051
      

#networks:
#  envoymesh: {}
