# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: postgres.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0epostgres.proto\x12\x08postgres\x1a\x1bgoogle/protobuf/empty.proto\"\x1d\n\x0cQueryRequest\x12\r\n\x05query\x18\x01 \x01(\t\"L\n\rQueryResponse\x12\x1b\n\x04rows\x18\x01 \x03(\x0b\x32\r.postgres.Row\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\r\n\x05\x65rror\x18\x03 \x01(\t\"&\n\x03Row\x12\x1f\n\x06values\x18\x01 \x03(\x0b\x32\x0f.postgres.Value\">\n\x05Value\x12\x13\n\x0b\x63olumn_name\x18\x01 \x01(\t\x12\x11\n\tdata_type\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\t2T\n\x0fPostgresService\x12\x41\n\x0c\x45xecuteQuery\x12\x16.postgres.QueryRequest\x1a\x17.postgres.QueryResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'postgres_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _QUERYREQUEST._serialized_start=57
  _QUERYREQUEST._serialized_end=86
  _QUERYRESPONSE._serialized_start=88
  _QUERYRESPONSE._serialized_end=164
  _ROW._serialized_start=166
  _ROW._serialized_end=204
  _VALUE._serialized_start=206
  _VALUE._serialized_end=268
  _POSTGRESSERVICE._serialized_start=270
  _POSTGRESSERVICE._serialized_end=354
# @@protoc_insertion_point(module_scope)
