# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import postgres_pb2 as postgres__pb2


class PostgresServiceStub(object):
    """Define the gRPC service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteQuery = channel.unary_unary(
                '/postgres.PostgresService/ExecuteQuery',
                request_serializer=postgres__pb2.QueryRequest.SerializeToString,
                response_deserializer=postgres__pb2.QueryResponse.FromString,
                )


class PostgresServiceServicer(object):
    """Define the gRPC service
    """

    def ExecuteQuery(self, request, context):
        """Define the RPC method to execute a PostgreSQL query
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PostgresServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteQuery,
                    request_deserializer=postgres__pb2.QueryRequest.FromString,
                    response_serializer=postgres__pb2.QueryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'postgres.PostgresService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PostgresService(object):
    """Define the gRPC service
    """

    @staticmethod
    def ExecuteQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/postgres.PostgresService/ExecuteQuery',
            postgres__pb2.QueryRequest.SerializeToString,
            postgres__pb2.QueryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
