static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 80
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          codec_type: auto
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: backend
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/helloworld.Greeter/"
#                 prefix: "/"
                  headers:
                  - name: content-type
                    value: application/grpc
                route:
                  cluster: helloworld
          http_filters:
          - name: envoy.router
            config: {}

  clusters:
  - name: helloworld
    connect_timeout: 0.25s
    lb_policy: round_robin
    http2_protocol_options: {}
    outlier_detection:
      max_ejection_percent: 100
    type: EDS
    eds_cluster_config:
      eds_config:
        path: "/config/eds.yaml"

admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8001
